import "../styles/globals.css";
import type { Metadata } from "next";
import { ReactQueryProvider } from "@/utils/ReactQueryProvider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Note App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html>
        <body>
          <div className="container">
            <div className="header">
              <h1>노트 앱</h1>
            </div>
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
